# map
TILE_SCALING = 2
TILE_SIZE = 32
TILEMAP_WIDTH = 30
TILEMAP_HEIGHT = 30
MAP_WIDTH = 960 * 30 * TILE_SCALING
MAP_HEIGHT = 720 * 30 * TILE_SCALING
SINGLE_MAP_WIDTH = TILEMAP_WIDTH * TILE_SCALING * TILE_SIZE
SINGLE_MAP_HEIGHT = TILEMAP_HEIGHT * TILE_SCALING * TILE_SIZE

# inventory
ROW_COUNT = 4
COLUMN_COUNT = 3
WIDTH = 130
HEIGHT = 130
MARGIN = 5

# screen settings
FULLSCREEN = True
VSYNC = True
SCREEN_HEIGHT = 0
SCREEN_WIDTH = 0

# server
SERVER_PORT = 1354
