TILE_SCALING = 2
TILE_SIZE = 32
TILEMAP_WIDTH = 30
TILEMAP_HEIGHT = 30
MAP_WIDTH = TILEMAP_WIDTH * TILE_SCALING * TILE_SIZE
MAP_HEIGHT = TILEMAP_HEIGHT * TILE_SCALING * TILE_SIZE
VERTICAL_OFFSET = 45
HEALTH_POINTS = 50
OUTER_RECTANGLE_WIDTH = 160
OUTER_RECTANGLE_HEIGHT = INNER_RECTANGLE_HEIGHT = 25
OUTER_RECTANGLE_THICKNESS = 2
INNER_RECTANGLE_COLOR = (36, 93, 45)
SCALE_HP_TO_HB = 1.6  # Scaling the health points to fit properly in the health bar
FULL_HEALTH = 100
