# map
TILE_SCALING = 2
TILE_SIZE = 32
TILEMAP_WIDTH = 30
TILEMAP_HEIGHT = 30
MAP_WIDTH = TILEMAP_WIDTH * TILE_SCALING * TILE_SIZE
MAP_HEIGHT = TILEMAP_HEIGHT * TILE_SCALING * TILE_SIZE


# inventory
ROW_COUNT = 3
COLUMN_COUNT = 3
WIDTH = 130
HEIGHT = 130
MARGIN = 5


# screen settings
SCREEN_HEIGHT = 0
SCREEN_WIDTH = 0
